/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayHardIndexRouteImport } from './routes/play.hard.index'
import { Route as PlaySeedResultRouteImport } from './routes/play.$seed.result'
import { Route as PlaySeedNRouteImport } from './routes/play.$seed.$n'
import { Route as PlayHardSeedResultRouteImport } from './routes/play.hard.$seed.result'
import { Route as PlayHardSeedNRouteImport } from './routes/play.hard.$seed.$n'

const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHardIndexRoute = PlayHardIndexRouteImport.update({
  id: '/play/hard/',
  path: '/play/hard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySeedResultRoute = PlaySeedResultRouteImport.update({
  id: '/play/$seed/result',
  path: '/play/$seed/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySeedNRoute = PlaySeedNRouteImport.update({
  id: '/play/$seed/$n',
  path: '/play/$seed/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHardSeedResultRoute = PlayHardSeedResultRouteImport.update({
  id: '/play/hard/$seed/result',
  path: '/play/hard/$seed/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHardSeedNRoute = PlayHardSeedNRouteImport.update({
  id: '/play/hard/$seed/$n',
  path: '/play/hard/$seed/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/play/': typeof PlayIndexRoute
  '/play/$seed/$n': typeof PlaySeedNRoute
  '/play/$seed/result': typeof PlaySeedResultRoute
  '/play/hard/': typeof PlayHardIndexRoute
  '/play/hard/$seed/$n': typeof PlayHardSeedNRoute
  '/play/hard/$seed/result': typeof PlayHardSeedResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/play': typeof PlayIndexRoute
  '/play/$seed/$n': typeof PlaySeedNRoute
  '/play/$seed/result': typeof PlaySeedResultRoute
  '/play/hard': typeof PlayHardIndexRoute
  '/play/hard/$seed/$n': typeof PlayHardSeedNRoute
  '/play/hard/$seed/result': typeof PlayHardSeedResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/play/': typeof PlayIndexRoute
  '/play/$seed/$n': typeof PlaySeedNRoute
  '/play/$seed/result': typeof PlaySeedResultRoute
  '/play/hard/': typeof PlayHardIndexRoute
  '/play/hard/$seed/$n': typeof PlayHardSeedNRoute
  '/play/hard/$seed/result': typeof PlayHardSeedResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sets'
    | '/play/'
    | '/play/$seed/$n'
    | '/play/$seed/result'
    | '/play/hard/'
    | '/play/hard/$seed/$n'
    | '/play/hard/$seed/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sets'
    | '/play'
    | '/play/$seed/$n'
    | '/play/$seed/result'
    | '/play/hard'
    | '/play/hard/$seed/$n'
    | '/play/hard/$seed/result'
  id:
    | '__root__'
    | '/'
    | '/sets'
    | '/play/'
    | '/play/$seed/$n'
    | '/play/$seed/result'
    | '/play/hard/'
    | '/play/hard/$seed/$n'
    | '/play/hard/$seed/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetsRoute: typeof SetsRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PlaySeedNRoute: typeof PlaySeedNRoute
  PlaySeedResultRoute: typeof PlaySeedResultRoute
  PlayHardIndexRoute: typeof PlayHardIndexRoute
  PlayHardSeedNRoute: typeof PlayHardSeedNRoute
  PlayHardSeedResultRoute: typeof PlayHardSeedResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/hard/': {
      id: '/play/hard/'
      path: '/play/hard'
      fullPath: '/play/hard/'
      preLoaderRoute: typeof PlayHardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$seed/result': {
      id: '/play/$seed/result'
      path: '/play/$seed/result'
      fullPath: '/play/$seed/result'
      preLoaderRoute: typeof PlaySeedResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$seed/$n': {
      id: '/play/$seed/$n'
      path: '/play/$seed/$n'
      fullPath: '/play/$seed/$n'
      preLoaderRoute: typeof PlaySeedNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/hard/$seed/result': {
      id: '/play/hard/$seed/result'
      path: '/play/hard/$seed/result'
      fullPath: '/play/hard/$seed/result'
      preLoaderRoute: typeof PlayHardSeedResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/hard/$seed/$n': {
      id: '/play/hard/$seed/$n'
      path: '/play/hard/$seed/$n'
      fullPath: '/play/hard/$seed/$n'
      preLoaderRoute: typeof PlayHardSeedNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetsRoute: SetsRoute,
  PlayIndexRoute: PlayIndexRoute,
  PlaySeedNRoute: PlaySeedNRoute,
  PlaySeedResultRoute: PlaySeedResultRoute,
  PlayHardIndexRoute: PlayHardIndexRoute,
  PlayHardSeedNRoute: PlayHardSeedNRoute,
  PlayHardSeedResultRoute: PlayHardSeedResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
