/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PickIndexRouteImport } from './routes/pick/index'
import { Route as PlayHardIndexRouteImport } from './routes/play/hard/index'
import { Route as PickHardIndexRouteImport } from './routes/pick/hard/index'
import { Route as PlaySeedResultRouteImport } from './routes/play/$seed/result'
import { Route as PlaySeedNRouteImport } from './routes/play/$seed/$n'
import { Route as PickSeedResultRouteImport } from './routes/pick/$seed/result'
import { Route as PickSeedNRouteImport } from './routes/pick/$seed/$n'
import { Route as PlayHardSeedResultRouteImport } from './routes/play/hard/$seed/result'
import { Route as PlayHardSeedNRouteImport } from './routes/play/hard/$seed/$n'
import { Route as PickHardSeedResultRouteImport } from './routes/pick/hard/$seed/result'
import { Route as PickHardSeedNRouteImport } from './routes/pick/hard/$seed/$n'

const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickIndexRoute = PickIndexRouteImport.update({
  id: '/pick/',
  path: '/pick/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHardIndexRoute = PlayHardIndexRouteImport.update({
  id: '/play/hard/',
  path: '/play/hard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickHardIndexRoute = PickHardIndexRouteImport.update({
  id: '/pick/hard/',
  path: '/pick/hard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySeedResultRoute = PlaySeedResultRouteImport.update({
  id: '/play/$seed/result',
  path: '/play/$seed/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySeedNRoute = PlaySeedNRouteImport.update({
  id: '/play/$seed/$n',
  path: '/play/$seed/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const PickSeedResultRoute = PickSeedResultRouteImport.update({
  id: '/pick/$seed/result',
  path: '/pick/$seed/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PickSeedNRoute = PickSeedNRouteImport.update({
  id: '/pick/$seed/$n',
  path: '/pick/$seed/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHardSeedResultRoute = PlayHardSeedResultRouteImport.update({
  id: '/play/hard/$seed/result',
  path: '/play/hard/$seed/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHardSeedNRoute = PlayHardSeedNRouteImport.update({
  id: '/play/hard/$seed/$n',
  path: '/play/hard/$seed/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const PickHardSeedResultRoute = PickHardSeedResultRouteImport.update({
  id: '/pick/hard/$seed/result',
  path: '/pick/hard/$seed/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PickHardSeedNRoute = PickHardSeedNRouteImport.update({
  id: '/pick/hard/$seed/$n',
  path: '/pick/hard/$seed/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/pick/': typeof PickIndexRoute
  '/play/': typeof PlayIndexRoute
  '/pick/$seed/$n': typeof PickSeedNRoute
  '/pick/$seed/result': typeof PickSeedResultRoute
  '/play/$seed/$n': typeof PlaySeedNRoute
  '/play/$seed/result': typeof PlaySeedResultRoute
  '/pick/hard/': typeof PickHardIndexRoute
  '/play/hard/': typeof PlayHardIndexRoute
  '/pick/hard/$seed/$n': typeof PickHardSeedNRoute
  '/pick/hard/$seed/result': typeof PickHardSeedResultRoute
  '/play/hard/$seed/$n': typeof PlayHardSeedNRoute
  '/play/hard/$seed/result': typeof PlayHardSeedResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/pick': typeof PickIndexRoute
  '/play': typeof PlayIndexRoute
  '/pick/$seed/$n': typeof PickSeedNRoute
  '/pick/$seed/result': typeof PickSeedResultRoute
  '/play/$seed/$n': typeof PlaySeedNRoute
  '/play/$seed/result': typeof PlaySeedResultRoute
  '/pick/hard': typeof PickHardIndexRoute
  '/play/hard': typeof PlayHardIndexRoute
  '/pick/hard/$seed/$n': typeof PickHardSeedNRoute
  '/pick/hard/$seed/result': typeof PickHardSeedResultRoute
  '/play/hard/$seed/$n': typeof PlayHardSeedNRoute
  '/play/hard/$seed/result': typeof PlayHardSeedResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/pick/': typeof PickIndexRoute
  '/play/': typeof PlayIndexRoute
  '/pick/$seed/$n': typeof PickSeedNRoute
  '/pick/$seed/result': typeof PickSeedResultRoute
  '/play/$seed/$n': typeof PlaySeedNRoute
  '/play/$seed/result': typeof PlaySeedResultRoute
  '/pick/hard/': typeof PickHardIndexRoute
  '/play/hard/': typeof PlayHardIndexRoute
  '/pick/hard/$seed/$n': typeof PickHardSeedNRoute
  '/pick/hard/$seed/result': typeof PickHardSeedResultRoute
  '/play/hard/$seed/$n': typeof PlayHardSeedNRoute
  '/play/hard/$seed/result': typeof PlayHardSeedResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sets'
    | '/pick/'
    | '/play/'
    | '/pick/$seed/$n'
    | '/pick/$seed/result'
    | '/play/$seed/$n'
    | '/play/$seed/result'
    | '/pick/hard/'
    | '/play/hard/'
    | '/pick/hard/$seed/$n'
    | '/pick/hard/$seed/result'
    | '/play/hard/$seed/$n'
    | '/play/hard/$seed/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sets'
    | '/pick'
    | '/play'
    | '/pick/$seed/$n'
    | '/pick/$seed/result'
    | '/play/$seed/$n'
    | '/play/$seed/result'
    | '/pick/hard'
    | '/play/hard'
    | '/pick/hard/$seed/$n'
    | '/pick/hard/$seed/result'
    | '/play/hard/$seed/$n'
    | '/play/hard/$seed/result'
  id:
    | '__root__'
    | '/'
    | '/sets'
    | '/pick/'
    | '/play/'
    | '/pick/$seed/$n'
    | '/pick/$seed/result'
    | '/play/$seed/$n'
    | '/play/$seed/result'
    | '/pick/hard/'
    | '/play/hard/'
    | '/pick/hard/$seed/$n'
    | '/pick/hard/$seed/result'
    | '/play/hard/$seed/$n'
    | '/play/hard/$seed/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetsRoute: typeof SetsRoute
  PickIndexRoute: typeof PickIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PickSeedNRoute: typeof PickSeedNRoute
  PickSeedResultRoute: typeof PickSeedResultRoute
  PlaySeedNRoute: typeof PlaySeedNRoute
  PlaySeedResultRoute: typeof PlaySeedResultRoute
  PickHardIndexRoute: typeof PickHardIndexRoute
  PlayHardIndexRoute: typeof PlayHardIndexRoute
  PickHardSeedNRoute: typeof PickHardSeedNRoute
  PickHardSeedResultRoute: typeof PickHardSeedResultRoute
  PlayHardSeedNRoute: typeof PlayHardSeedNRoute
  PlayHardSeedResultRoute: typeof PlayHardSeedResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick/': {
      id: '/pick/'
      path: '/pick'
      fullPath: '/pick/'
      preLoaderRoute: typeof PickIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/hard/': {
      id: '/play/hard/'
      path: '/play/hard'
      fullPath: '/play/hard/'
      preLoaderRoute: typeof PlayHardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick/hard/': {
      id: '/pick/hard/'
      path: '/pick/hard'
      fullPath: '/pick/hard/'
      preLoaderRoute: typeof PickHardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$seed/result': {
      id: '/play/$seed/result'
      path: '/play/$seed/result'
      fullPath: '/play/$seed/result'
      preLoaderRoute: typeof PlaySeedResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$seed/$n': {
      id: '/play/$seed/$n'
      path: '/play/$seed/$n'
      fullPath: '/play/$seed/$n'
      preLoaderRoute: typeof PlaySeedNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick/$seed/result': {
      id: '/pick/$seed/result'
      path: '/pick/$seed/result'
      fullPath: '/pick/$seed/result'
      preLoaderRoute: typeof PickSeedResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick/$seed/$n': {
      id: '/pick/$seed/$n'
      path: '/pick/$seed/$n'
      fullPath: '/pick/$seed/$n'
      preLoaderRoute: typeof PickSeedNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/hard/$seed/result': {
      id: '/play/hard/$seed/result'
      path: '/play/hard/$seed/result'
      fullPath: '/play/hard/$seed/result'
      preLoaderRoute: typeof PlayHardSeedResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/hard/$seed/$n': {
      id: '/play/hard/$seed/$n'
      path: '/play/hard/$seed/$n'
      fullPath: '/play/hard/$seed/$n'
      preLoaderRoute: typeof PlayHardSeedNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick/hard/$seed/result': {
      id: '/pick/hard/$seed/result'
      path: '/pick/hard/$seed/result'
      fullPath: '/pick/hard/$seed/result'
      preLoaderRoute: typeof PickHardSeedResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick/hard/$seed/$n': {
      id: '/pick/hard/$seed/$n'
      path: '/pick/hard/$seed/$n'
      fullPath: '/pick/hard/$seed/$n'
      preLoaderRoute: typeof PickHardSeedNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetsRoute: SetsRoute,
  PickIndexRoute: PickIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  PickSeedNRoute: PickSeedNRoute,
  PickSeedResultRoute: PickSeedResultRoute,
  PlaySeedNRoute: PlaySeedNRoute,
  PlaySeedResultRoute: PlaySeedResultRoute,
  PickHardIndexRoute: PickHardIndexRoute,
  PlayHardIndexRoute: PlayHardIndexRoute,
  PickHardSeedNRoute: PickHardSeedNRoute,
  PickHardSeedResultRoute: PickHardSeedResultRoute,
  PlayHardSeedNRoute: PlayHardSeedNRoute,
  PlayHardSeedResultRoute: PlayHardSeedResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
